/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InvoicesGetAllResult,
    InvoicesGetAllResultFromJSON,
    InvoicesGetAllResultToJSON,
} from '../models';

export interface InvoiceGetRequest {
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class InvoiceApi extends runtime.BaseAPI {

    /**
     */
    async invoiceGetRaw(requestParameters: InvoiceGetRequest): Promise<runtime.ApiResponse<InvoicesGetAllResult>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Invoice`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoicesGetAllResultFromJSON(jsonValue));
    }

    /**
     */
    async invoiceGet(requestParameters: InvoiceGetRequest): Promise<InvoicesGetAllResult> {
        const response = await this.invoiceGetRaw(requestParameters);
        return await response.value();
    }

}
