/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomersGetAllModel
 */
export interface CustomersGetAllModel {
    /**
     * 
     * @type {number}
     * @memberof CustomersGetAllModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CustomersGetAllModel
     */
    name: string;
}

export function CustomersGetAllModelFromJSON(json: any): CustomersGetAllModel {
    return CustomersGetAllModelFromJSONTyped(json, false);
}

export function CustomersGetAllModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersGetAllModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CustomersGetAllModelToJSON(value?: CustomersGetAllModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


