/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomersModel,
    CustomersModelFromJSON,
    CustomersModelFromJSONTyped,
    CustomersModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomersUpdateResult
 */
export interface CustomersUpdateResult {
    /**
     * 
     * @type {CustomersModel}
     * @memberof CustomersUpdateResult
     */
    customer: CustomersModel;
}

export function CustomersUpdateResultFromJSON(json: any): CustomersUpdateResult {
    return CustomersUpdateResultFromJSONTyped(json, false);
}

export function CustomersUpdateResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersUpdateResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer': CustomersModelFromJSON(json['customer']),
    };
}

export function CustomersUpdateResultToJSON(value?: CustomersUpdateResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer': CustomersModelToJSON(value.customer),
    };
}


