/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DomainAddress,
    DomainAddressFromJSON,
    DomainAddressFromJSONTyped,
    DomainAddressToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomersUpdateForm
 */
export interface CustomersUpdateForm {
    /**
     * 
     * @type {string}
     * @memberof CustomersUpdateForm
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CustomersUpdateForm
     */
    phone?: string | null;
    /**
     * 
     * @type {DomainAddress}
     * @memberof CustomersUpdateForm
     */
    address: DomainAddress;
}

export function CustomersUpdateFormFromJSON(json: any): CustomersUpdateForm {
    return CustomersUpdateFormFromJSONTyped(json, false);
}

export function CustomersUpdateFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersUpdateForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'address': DomainAddressFromJSON(json['address']),
    };
}

export function CustomersUpdateFormToJSON(value?: CustomersUpdateForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'phone': value.phone,
        'address': DomainAddressToJSON(value.address),
    };
}


