/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomersModel
 */
export interface CustomersModel {
    /**
     * 
     * @type {number}
     * @memberof CustomersModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CustomersModel
     */
    name: string;
}

export function CustomersModelFromJSON(json: any): CustomersModel {
    return CustomersModelFromJSONTyped(json, false);
}

export function CustomersModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CustomersModelToJSON(value?: CustomersModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


