/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomersGetAllModel,
    CustomersGetAllModelFromJSON,
    CustomersGetAllModelFromJSONTyped,
    CustomersGetAllModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomersGetAllResult
 */
export interface CustomersGetAllResult {
    /**
     * 
     * @type {number}
     * @memberof CustomersGetAllResult
     */
    readonly page: number;
    /**
     * 
     * @type {number}
     * @memberof CustomersGetAllResult
     */
    readonly pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof CustomersGetAllResult
     */
    readonly pageCount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomersGetAllResult
     */
    readonly count: number;
    /**
     * 
     * @type {number}
     * @memberof CustomersGetAllResult
     */
    readonly total: number;
    /**
     * 
     * @type {Array<CustomersGetAllModel>}
     * @memberof CustomersGetAllResult
     */
    readonly items: Array<CustomersGetAllModel>;
}

export function CustomersGetAllResultFromJSON(json: any): CustomersGetAllResult {
    return CustomersGetAllResultFromJSONTyped(json, false);
}

export function CustomersGetAllResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersGetAllResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'pageCount': json['pageCount'],
        'count': json['count'],
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(CustomersGetAllModelFromJSON)),
    };
}

export function CustomersGetAllResultToJSON(value?: CustomersGetAllResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


