/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomersCreateForm
 */
export interface CustomersCreateForm {
    /**
     * 
     * @type {string}
     * @memberof CustomersCreateForm
     */
    name: string;
}

export function CustomersCreateFormFromJSON(json: any): CustomersCreateForm {
    return CustomersCreateFormFromJSONTyped(json, false);
}

export function CustomersCreateFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersCreateForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CustomersCreateFormToJSON(value?: CustomersCreateForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


