/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomersGetByIdModel,
    CustomersGetByIdModelFromJSON,
    CustomersGetByIdModelFromJSONTyped,
    CustomersGetByIdModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomersGetByIdResult
 */
export interface CustomersGetByIdResult {
    /**
     * 
     * @type {CustomersGetByIdModel}
     * @memberof CustomersGetByIdResult
     */
    customer: CustomersGetByIdModel;
}

export function CustomersGetByIdResultFromJSON(json: any): CustomersGetByIdResult {
    return CustomersGetByIdResultFromJSONTyped(json, false);
}

export function CustomersGetByIdResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersGetByIdResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer': CustomersGetByIdModelFromJSON(json['customer']),
    };
}

export function CustomersGetByIdResultToJSON(value?: CustomersGetByIdResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer': CustomersGetByIdModelToJSON(value.customer),
    };
}


