/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainAddress
 */
export interface DomainAddress {
    /**
     * 
     * @type {string}
     * @memberof DomainAddress
     */
    line1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DomainAddress
     */
    line2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DomainAddress
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DomainAddress
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DomainAddress
     */
    zip?: string | null;
}

export function DomainAddressFromJSON(json: any): DomainAddress {
    return DomainAddressFromJSONTyped(json, false);
}

export function DomainAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'line1': !exists(json, 'line1') ? undefined : json['line1'],
        'line2': !exists(json, 'line2') ? undefined : json['line2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
    };
}

export function DomainAddressToJSON(value?: DomainAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'line1': value.line1,
        'line2': value.line2,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
    };
}


