/* tslint:disable */
/* eslint-disable */
/**
 * Playground
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InvoicesModel,
    InvoicesModelFromJSON,
    InvoicesModelFromJSONTyped,
    InvoicesModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface InvoicesGetAllResult
 */
export interface InvoicesGetAllResult {
    /**
     * 
     * @type {number}
     * @memberof InvoicesGetAllResult
     */
    readonly page: number;
    /**
     * 
     * @type {number}
     * @memberof InvoicesGetAllResult
     */
    readonly pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof InvoicesGetAllResult
     */
    readonly pageCount: number;
    /**
     * 
     * @type {number}
     * @memberof InvoicesGetAllResult
     */
    readonly count: number;
    /**
     * 
     * @type {number}
     * @memberof InvoicesGetAllResult
     */
    readonly total: number;
    /**
     * 
     * @type {Array<InvoicesModel>}
     * @memberof InvoicesGetAllResult
     */
    readonly items: Array<InvoicesModel>;
}

export function InvoicesGetAllResultFromJSON(json: any): InvoicesGetAllResult {
    return InvoicesGetAllResultFromJSONTyped(json, false);
}

export function InvoicesGetAllResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicesGetAllResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'pageCount': json['pageCount'],
        'count': json['count'],
        'total': json['total'],
        'items': ((json['items'] as Array<any>).map(InvoicesModelFromJSON)),
    };
}

export function InvoicesGetAllResultToJSON(value?: InvoicesGetAllResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


